[2024-02-29T07:45:09.820+0000] {processor.py:161} INFO - Started process (PID=1382) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:09.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:45:09.822+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:09.821+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:09.833+0000] {processor.py:840} INFO - DAG(s) 'Day_3_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:09.980+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:09.979+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:45:10.026+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:10.025+0000] {dag.py:3820} INFO - Setting next_dagrun for Day_3_dag to 2024-02-03T18:00:00+00:00, run_after=2024-03-03T18:00:00+00:00
[2024-02-29T07:45:10.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.233 seconds
[2024-02-29T07:45:22.084+0000] {processor.py:161} INFO - Started process (PID=1405) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:22.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:45:22.085+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:22.085+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:22.095+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:22.195+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:22.194+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:weather_api_dag
[2024-02-29T07:45:22.209+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:22.209+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:weather_api_dag
[2024-02-29T07:45:22.219+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:22.219+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:weather_api_dag
[2024-02-29T07:45:22.219+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:22.219+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:45:22.228+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:22.228+0000] {dag.py:3055} INFO - Creating ORM DAG for weather_api_dag
[2024-02-29T07:45:22.236+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:22.236+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-03T18:00:00+00:00, run_after=2024-03-03T18:00:00+00:00
[2024-02-29T07:45:22.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.172 seconds
[2024-02-29T07:45:43.384+0000] {processor.py:161} INFO - Started process (PID=1432) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:43.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:45:43.386+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:43.386+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:43.394+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:43.392+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 738, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-02-29T07:45:43.394+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:43.420+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.039 seconds
[2024-02-29T07:45:45.455+0000] {processor.py:161} INFO - Started process (PID=1442) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:45.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:45:45.456+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:45.456+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:45.466+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:45.476+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:45.476+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:45:45.495+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:45.495+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-20T00:00:00+00:00, run_after=2024-01-20T01:00:00+00:00
[2024-02-29T07:45:45.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.073 seconds
[2024-02-29T07:45:49.527+0000] {processor.py:161} INFO - Started process (PID=1447) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:49.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:45:49.529+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:49.528+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:49.538+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:45:49.549+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:49.549+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:45:49.567+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:45:49.567+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:45:49.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.064 seconds
[2024-02-29T07:46:19.763+0000] {processor.py:161} INFO - Started process (PID=1491) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:19.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:46:19.773+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:19.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:19.790+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:19.944+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:19.943+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:46:19.965+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:19.965+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:46:19.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.230 seconds
[2024-02-29T07:46:34.013+0000] {processor.py:161} INFO - Started process (PID=1515) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:34.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:46:34.014+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:34.014+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:34.020+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:34.020+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 14, in <module>
    my_first_task >> my_second_task
NameError: name 'my_first_task' is not defined
[2024-02-29T07:46:34.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:34.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.031 seconds
[2024-02-29T07:46:38.033+0000] {processor.py:161} INFO - Started process (PID=1520) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:38.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:46:38.034+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:38.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:38.040+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:38.039+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 14, in <module>
    my_first_task >> my_second_task
NameError: name 'my_first_task' is not defined
[2024-02-29T07:46:38.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:38.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.035 seconds
[2024-02-29T07:46:42.100+0000] {processor.py:161} INFO - Started process (PID=1525) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:42.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:46:42.101+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:42.101+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:42.107+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:42.106+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 14, in <module>
    my_first_task >> my_second_task
NameError: name 'my_first_task' is not defined
[2024-02-29T07:46:42.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:42.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.056 seconds
[2024-02-29T07:46:47.200+0000] {processor.py:161} INFO - Started process (PID=1543) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:47.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:46:47.201+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:47.201+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:47.207+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:47.207+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 14, in <module>
    my_first_task >> my_second_task
NameError: name 'my_first_task' is not defined
[2024-02-29T07:46:47.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:47.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.030 seconds
[2024-02-29T07:46:51.221+0000] {processor.py:161} INFO - Started process (PID=1548) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:51.222+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:46:51.224+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:51.223+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:51.232+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:51.231+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 14, in <module>
    start >> my_second_task
NameError: name 'my_second_task' is not defined
[2024-02-29T07:46:51.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:51.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.044 seconds
[2024-02-29T07:46:58.349+0000] {processor.py:161} INFO - Started process (PID=1566) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:58.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:46:58.360+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:58.360+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:58.374+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:46:58.596+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:58.596+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:46:58.621+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:46:58.621+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:46:58.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.327 seconds
[2024-02-29T07:47:00.369+0000] {processor.py:161} INFO - Started process (PID=1571) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:00.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:00.370+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:00.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:00.379+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:00.391+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:00.390+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:47:00.409+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:00.409+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:47:00.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.063 seconds
[2024-02-29T07:47:01.383+0000] {processor.py:161} INFO - Started process (PID=1576) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:01.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:01.385+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:01.385+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:01.399+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:01.413+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:01.412+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:47:01.441+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:01.440+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:47:01.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.088 seconds
[2024-02-29T07:47:03.513+0000] {processor.py:161} INFO - Started process (PID=1586) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:03.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:03.514+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:03.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:03.520+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:03.519+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    Py
NameError: name 'Py' is not defined
[2024-02-29T07:47:03.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:03.540+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.030 seconds
[2024-02-29T07:47:04.566+0000] {processor.py:161} INFO - Started process (PID=1591) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:04.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:04.567+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:04.567+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:04.573+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:04.572+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    Pyth
NameError: name 'Pyth' is not defined
[2024-02-29T07:47:04.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:04.594+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.031 seconds
[2024-02-29T07:47:06.620+0000] {processor.py:161} INFO - Started process (PID=1596) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:06.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:06.621+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:06.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:06.626+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:06.626+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    Python
NameError: name 'Python' is not defined
[2024-02-29T07:47:06.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:06.647+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.030 seconds
[2024-02-29T07:47:11.660+0000] {processor.py:161} INFO - Started process (PID=1610) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:11.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:11.662+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:11.661+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:11.669+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:11.668+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    PythonOpar
NameError: name 'PythonOpar' is not defined
[2024-02-29T07:47:11.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:11.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.038 seconds
[2024-02-29T07:47:14.695+0000] {processor.py:161} INFO - Started process (PID=1615) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:14.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:14.697+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:14.697+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:14.705+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:14.705+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    PythonOper
NameError: name 'PythonOper' is not defined
[2024-02-29T07:47:14.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:14.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.067 seconds
[2024-02-29T07:47:16.848+0000] {processor.py:161} INFO - Started process (PID=1625) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:16.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:16.850+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:16.850+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:16.867+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:16.866+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    PythonOperatpr
NameError: name 'PythonOperatpr' is not defined
[2024-02-29T07:47:16.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:16.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.083 seconds
[2024-02-29T07:47:18.937+0000] {processor.py:161} INFO - Started process (PID=1630) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:18.938+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:18.939+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:18.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:18.947+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:18.946+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    PythonOperator
NameError: name 'PythonOperator' is not defined
[2024-02-29T07:47:18.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:18.975+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.041 seconds
[2024-02-29T07:47:24.108+0000] {processor.py:161} INFO - Started process (PID=1649) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:24.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:24.109+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:24.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:24.122+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:24.120+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    PythonOperator()
NameError: name 'PythonOperator' is not defined
[2024-02-29T07:47:24.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:24.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.065 seconds
[2024-02-29T07:47:31.146+0000] {processor.py:161} INFO - Started process (PID=1654) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:31.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:31.147+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:31.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:31.154+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:31.153+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    get_weatherPythonOperator()
NameError: name 'get_weatherPythonOperator' is not defined
[2024-02-29T07:47:31.154+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:31.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.031 seconds
[2024-02-29T07:47:34.233+0000] {processor.py:161} INFO - Started process (PID=1664) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:34.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:34.234+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:34.234+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:34.239+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:34.239+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    get_weather_data=PythonOperator()
NameError: name 'PythonOperator' is not defined
[2024-02-29T07:47:34.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:34.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.029 seconds
[2024-02-29T07:47:36.303+0000] {processor.py:161} INFO - Started process (PID=1677) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:36.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:36.312+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:36.311+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:36.337+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:36.336+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    get_weather_data = PythonOperator()
NameError: name 'PythonOperator' is not defined
[2024-02-29T07:47:36.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:36.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.099 seconds
[2024-02-29T07:47:39.328+0000] {processor.py:161} INFO - Started process (PID=1682) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:39.328+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:39.329+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:39.329+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:39.334+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:39.334+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    get_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-29T07:47:39.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:39.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.030 seconds
[2024-02-29T07:47:49.437+0000] {processor.py:161} INFO - Started process (PID=1700) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:49.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:49.438+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:49.438+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:49.446+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:49.445+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    get_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-29T07:47:49.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:49.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.049 seconds
[2024-02-29T07:47:52.492+0000] {processor.py:161} INFO - Started process (PID=1705) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:52.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:47:52.494+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:52.493+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:52.499+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:47:52.498+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 15
    )
    ^
SyntaxError: invalid syntax
[2024-02-29T07:47:52.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:47:52.533+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.045 seconds
[2024-02-29T07:48:00.618+0000] {processor.py:161} INFO - Started process (PID=1715) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:00.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:48:00.622+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:00.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:00.632+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:00.631+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    get_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-29T07:48:00.632+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:00.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.047 seconds
[2024-02-29T07:48:03.714+0000] {processor.py:161} INFO - Started process (PID=1728) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:03.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:48:03.720+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:03.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:03.764+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:03.754+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    get_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-29T07:48:03.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:03.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.090 seconds
[2024-02-29T07:48:06.869+0000] {processor.py:161} INFO - Started process (PID=1738) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:06.870+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:48:06.870+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:06.870+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:06.873+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:06.872+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 15
    python
    ^
SyntaxError: positional argument follows keyword argument
[2024-02-29T07:48:06.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:06.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.029 seconds
[2024-02-29T07:48:10.891+0000] {processor.py:161} INFO - Started process (PID=1743) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:10.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:48:10.893+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:10.892+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:10.896+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:10.895+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 15
    python_callable
    ^
SyntaxError: positional argument follows keyword argument
[2024-02-29T07:48:10.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:10.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.040 seconds
[2024-02-29T07:48:12.957+0000] {processor.py:161} INFO - Started process (PID=1748) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:12.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:48:12.958+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:12.958+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:12.960+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:12.960+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 15
    python_callable=,
                    ^
SyntaxError: invalid syntax
[2024-02-29T07:48:12.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:12.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.027 seconds
[2024-02-29T07:48:43.216+0000] {processor.py:161} INFO - Started process (PID=1793) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:43.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:48:43.217+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:43.217+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:43.219+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:43.219+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 15
    python_callable=,
                    ^
SyntaxError: invalid syntax
[2024-02-29T07:48:43.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:43.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.026 seconds
[2024-02-29T07:48:46.233+0000] {processor.py:161} INFO - Started process (PID=1798) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:46.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:48:46.235+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:46.235+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:46.242+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:46.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    get_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-29T07:48:46.243+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:46.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.040 seconds
[2024-02-29T07:48:52.317+0000] {processor.py:161} INFO - Started process (PID=1808) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:52.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:48:52.319+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:52.319+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:52.328+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:48:52.327+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    get_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-29T07:48:52.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:48:52.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.037 seconds
[2024-02-29T07:49:22.599+0000] {processor.py:161} INFO - Started process (PID=1854) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:22.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:49:22.600+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:22.600+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:22.606+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:22.605+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 13, in <module>
    get_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-29T07:49:22.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:22.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.031 seconds
[2024-02-29T07:49:24.659+0000] {processor.py:161} INFO - Started process (PID=1864) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:24.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:49:24.660+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:24.660+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:24.662+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:24.662+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 4
    from
       ^
SyntaxError: invalid syntax
[2024-02-29T07:49:24.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:24.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.028 seconds
[2024-02-29T07:49:27.703+0000] {processor.py:161} INFO - Started process (PID=1869) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:27.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:49:27.704+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:27.704+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:27.707+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:27.706+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 4
    from airflow
               ^
SyntaxError: invalid syntax
[2024-02-29T07:49:27.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:27.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.029 seconds
[2024-02-29T07:49:30.741+0000] {processor.py:161} INFO - Started process (PID=1874) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:30.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:49:30.742+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:30.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:30.745+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:30.744+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 4
    from airflow.operator
                        ^
SyntaxError: invalid syntax
[2024-02-29T07:49:30.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:30.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.026 seconds
[2024-02-29T07:49:36.806+0000] {processor.py:161} INFO - Started process (PID=1892) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:36.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:49:36.807+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:36.807+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:36.809+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:36.809+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 4
    from airflow.operators.python import
                                        ^
SyntaxError: invalid syntax
[2024-02-29T07:49:36.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:36.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.028 seconds
[2024-02-29T07:49:39.827+0000] {processor.py:161} INFO - Started process (PID=1897) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:39.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:49:39.829+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:39.829+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:39.834+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:39.833+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 4, in <module>
    from airflow.operators.python import Python
ImportError: cannot import name 'Python' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py)
[2024-02-29T07:49:39.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:39.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.034 seconds
[2024-02-29T07:49:42.877+0000] {processor.py:161} INFO - Started process (PID=1902) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:42.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:49:42.879+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:42.879+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:42.888+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:42.887+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 16, in <module>
    python_callable=_get_weather_data,
NameError: name '_get_weather_data' is not defined
[2024-02-29T07:49:42.888+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:42.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.038 seconds
[2024-02-29T07:49:59.158+0000] {processor.py:161} INFO - Started process (PID=1933) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:59.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:49:59.172+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:59.172+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:59.175+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:49:59.174+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 7
    def _get
           ^
SyntaxError: invalid syntax
[2024-02-29T07:49:59.187+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:49:59.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.104 seconds
[2024-02-29T07:50:04.158+0000] {processor.py:161} INFO - Started process (PID=1938) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:04.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:50:04.160+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:04.160+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:04.162+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:04.162+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 7
    def _get_weather_data
                        ^
SyntaxError: invalid syntax
[2024-02-29T07:50:04.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:04.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.027 seconds
[2024-02-29T07:50:05.235+0000] {processor.py:161} INFO - Started process (PID=1946) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:05.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:50:05.237+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:05.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:05.240+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:05.239+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 7
    def _get_weather_data()
                          ^
SyntaxError: invalid syntax
[2024-02-29T07:50:05.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:05.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.043 seconds
[2024-02-29T07:50:07.321+0000] {processor.py:161} INFO - Started process (PID=1953) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:07.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:50:07.323+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:07.322+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:07.325+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:07.325+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 9
    with DAG(
    ^
IndentationError: expected an indented block
[2024-02-29T07:50:07.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:07.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.029 seconds
[2024-02-29T07:50:10.359+0000] {processor.py:161} INFO - Started process (PID=1967) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:10.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:50:10.361+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:10.361+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:10.381+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:10.592+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:10.591+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:50:10.633+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:10.632+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:50:10.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.307 seconds
[2024-02-29T07:50:40.723+0000] {processor.py:161} INFO - Started process (PID=2005) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:40.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:50:40.725+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:40.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:40.734+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:50:40.755+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:40.755+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:50:40.772+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:50:40.772+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:50:40.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.072 seconds
[2024-02-29T07:51:11.003+0000] {processor.py:161} INFO - Started process (PID=2042) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:51:11.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:51:11.005+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:51:11.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:51:11.014+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:51:11.035+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:51:11.035+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:51:11.052+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:51:11.052+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:51:11.070+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.070 seconds
[2024-02-29T07:51:41.310+0000] {processor.py:161} INFO - Started process (PID=2086) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:51:41.310+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:51:41.314+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:51:41.314+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:51:41.327+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:51:41.360+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:51:41.360+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:51:41.390+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:51:41.389+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:51:41.424+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.127 seconds
[2024-02-29T07:52:11.656+0000] {processor.py:161} INFO - Started process (PID=2123) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:52:11.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:52:11.657+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:52:11.657+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:52:11.668+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:52:11.689+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:52:11.689+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:52:11.710+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:52:11.710+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:52:11.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.075 seconds
[2024-02-29T07:52:41.939+0000] {processor.py:161} INFO - Started process (PID=2160) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:52:41.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:52:41.941+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:52:41.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:52:41.950+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:52:41.970+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:52:41.970+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:52:41.989+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:52:41.988+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:52:42.007+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.071 seconds
[2024-02-29T07:53:12.306+0000] {processor.py:161} INFO - Started process (PID=2204) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:12.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:53:12.308+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:12.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:12.317+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:12.339+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:12.338+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:53:12.359+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:12.359+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:53:12.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.074 seconds
[2024-02-29T07:53:20.431+0000] {processor.py:161} INFO - Started process (PID=2222) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:20.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:53:20.433+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:20.433+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:20.438+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:20.437+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 18, in <module>
    response = requests.get(url, params=payload)
NameError: name 'requests' is not defined
[2024-02-29T07:53:20.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:20.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.037 seconds
[2024-02-29T07:53:23.453+0000] {processor.py:161} INFO - Started process (PID=2228) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:23.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:53:23.455+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:23.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:23.459+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:23.459+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 18, in <module>
    response = requests.get(url, params=payload)
NameError: name 'requests' is not defined
[2024-02-29T07:53:23.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:23.488+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.038 seconds
[2024-02-29T07:53:27.535+0000] {processor.py:161} INFO - Started process (PID=2238) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:27.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:53:27.537+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:27.536+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:27.540+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:27.539+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 18, in <module>
    response = requests.get(url, params=payload)
NameError: name 'requests' is not defined
[2024-02-29T07:53:27.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:27.559+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.027 seconds
[2024-02-29T07:53:34.612+0000] {processor.py:161} INFO - Started process (PID=2251) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:34.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:53:34.613+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:34.613+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:34.635+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:34.634+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 18, in <module>
    response = requests.get(url, params=payload)
NameError: name 'requests' is not defined
[2024-02-29T07:53:34.636+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:34.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.065 seconds
[2024-02-29T07:53:35.630+0000] {processor.py:161} INFO - Started process (PID=2256) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:35.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:53:35.632+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:35.632+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:35.637+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:35.636+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 19, in <module>
    print(response.url)
NameError: name 'response' is not defined
[2024-02-29T07:53:35.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:35.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.036 seconds
[2024-02-29T07:53:37.654+0000] {processor.py:161} INFO - Started process (PID=2261) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:37.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:53:37.656+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:37.656+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:37.660+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:37.660+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/weather_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_api_dag.py", line 22, in <module>
    print(data)
NameError: name 'data' is not defined
[2024-02-29T07:53:37.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:37.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.040 seconds
[2024-02-29T07:53:38.720+0000] {processor.py:161} INFO - Started process (PID=2271) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:38.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:53:38.721+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:38.721+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:38.731+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:53:38.752+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:38.752+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:53:38.770+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:53:38.770+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:53:38.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.078 seconds
[2024-02-29T07:54:09.067+0000] {processor.py:161} INFO - Started process (PID=2310) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:54:09.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:54:09.069+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:54:09.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:54:09.078+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:54:09.099+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:54:09.099+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:54:09.117+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:54:09.117+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:54:09.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.071 seconds
[2024-02-29T07:54:18.207+0000] {processor.py:161} INFO - Started process (PID=2323) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:54:18.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:54:18.209+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:54:18.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:54:18.222+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:54:18.253+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:54:18.253+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:54:18.273+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:54:18.273+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:54:18.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.090 seconds
[2024-02-29T07:54:48.516+0000] {processor.py:161} INFO - Started process (PID=2359) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:54:48.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:54:48.517+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:54:48.517+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:54:48.527+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:54:48.554+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:54:48.554+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:54:48.580+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:54:48.580+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-27T00:00:00+00:00, run_after=2024-01-27T01:00:00+00:00
[2024-02-29T07:54:48.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.086 seconds
[2024-02-29T07:55:19.023+0000] {processor.py:161} INFO - Started process (PID=2487) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:55:19.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:55:19.025+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:55:19.025+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:55:19.054+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:55:19.084+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:55:19.084+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:55:19.138+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:55:19.138+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-28T20:00:00+00:00, run_after=2024-01-28T21:00:00+00:00
[2024-02-29T07:55:19.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.158 seconds
[2024-02-29T07:55:50.109+0000] {processor.py:161} INFO - Started process (PID=2615) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:55:50.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:55:50.111+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:55:50.110+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:55:50.194+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:55:50.253+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:55:50.253+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:55:50.408+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:55:50.408+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-01-30T20:00:00+00:00, run_after=2024-01-30T21:00:00+00:00
[2024-02-29T07:55:50.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.373 seconds
[2024-02-29T07:56:20.716+0000] {processor.py:161} INFO - Started process (PID=2740) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:56:20.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:56:20.746+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:56:20.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:56:20.892+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:56:21.010+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:56:21.010+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:56:21.667+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:56:21.666+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-01T18:00:00+00:00, run_after=2024-02-01T19:00:00+00:00
[2024-02-29T07:56:21.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 1.265 seconds
[2024-02-29T07:56:52.235+0000] {processor.py:161} INFO - Started process (PID=2861) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:56:52.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:56:52.237+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:56:52.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:56:52.253+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:56:52.290+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:56:52.290+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:56:52.335+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:56:52.335+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-03T10:00:00+00:00, run_after=2024-02-03T11:00:00+00:00
[2024-02-29T07:56:52.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.128 seconds
[2024-02-29T07:57:22.744+0000] {processor.py:161} INFO - Started process (PID=2985) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:22.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:57:22.760+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:22.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:22.802+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:22.872+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:22.872+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:57:23.004+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:23.004+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-05T06:00:00+00:00, run_after=2024-02-05T07:00:00+00:00
[2024-02-29T07:57:23.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.440 seconds
[2024-02-29T07:57:24.769+0000] {processor.py:161} INFO - Started process (PID=2999) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:24.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:57:24.771+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:24.771+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:24.781+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:24.807+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:24.807+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:57:24.826+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:24.826+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-05T07:00:00+00:00, run_after=2024-02-05T08:00:00+00:00
[2024-02-29T07:57:24.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.079 seconds
[2024-02-29T07:57:28.845+0000] {processor.py:161} INFO - Started process (PID=3017) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:28.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:57:28.849+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:28.849+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:28.887+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:28.985+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:28.985+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:57:29.042+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:29.042+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-05T11:00:00+00:00, run_after=2024-02-05T12:00:00+00:00
[2024-02-29T07:57:29.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.262 seconds
[2024-02-29T07:57:51.362+0000] {processor.py:161} INFO - Started process (PID=3106) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:51.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:57:51.370+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:51.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:51.397+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:51.595+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:51.594+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:57:52.026+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:52.026+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-06T22:00:00+00:00, run_after=2024-02-06T23:00:00+00:00
[2024-02-29T07:57:52.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.839 seconds
[2024-02-29T07:57:55.347+0000] {processor.py:161} INFO - Started process (PID=3130) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:55.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:57:55.351+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:55.351+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:55.411+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:57:55.521+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:55.520+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:57:55.660+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:57:55.659+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-07T05:00:00+00:00, run_after=2024-02-07T06:00:00+00:00
[2024-02-29T07:57:55.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.415 seconds
[2024-02-29T07:58:03.516+0000] {processor.py:161} INFO - Started process (PID=3170) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:58:03.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:58:03.551+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:58:03.551+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:58:03.670+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:58:03.814+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:58:03.814+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:58:03.924+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:58:03.924+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-07T14:00:00+00:00, run_after=2024-02-07T15:00:00+00:00
[2024-02-29T07:58:04.015+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.529 seconds
[2024-02-29T07:58:34.652+0000] {processor.py:161} INFO - Started process (PID=3296) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:58:34.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:58:34.658+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:58:34.658+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:58:34.712+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:58:34.814+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:58:34.814+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:58:35.096+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:58:35.088+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-09T10:00:00+00:00, run_after=2024-02-09T11:00:00+00:00
[2024-02-29T07:58:35.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.544 seconds
[2024-02-29T07:59:05.291+0000] {processor.py:161} INFO - Started process (PID=3416) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:59:05.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:59:05.292+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:59:05.292+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:59:05.301+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:59:05.322+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:59:05.322+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:59:05.340+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:59:05.340+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-11T07:00:00+00:00, run_after=2024-02-11T08:00:00+00:00
[2024-02-29T07:59:05.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.070 seconds
[2024-02-29T07:59:35.840+0000] {processor.py:161} INFO - Started process (PID=3531) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:59:35.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T07:59:35.872+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:59:35.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:59:36.149+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T07:59:36.388+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:59:36.388+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T07:59:36.618+0000] {logging_mixin.py:188} INFO - [2024-02-29T07:59:36.618+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-13T01:00:00+00:00, run_after=2024-02-13T02:00:00+00:00
[2024-02-29T07:59:36.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.999 seconds
[2024-02-29T08:00:07.076+0000] {processor.py:161} INFO - Started process (PID=3650) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:00:07.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T08:00:07.079+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:00:07.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:00:07.118+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:00:07.158+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:00:07.157+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T08:00:07.199+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:00:07.198+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-14T16:00:00+00:00, run_after=2024-02-14T17:00:00+00:00
[2024-02-29T08:00:07.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.168 seconds
[2024-02-29T08:00:37.601+0000] {processor.py:161} INFO - Started process (PID=3747) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:00:37.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T08:00:37.603+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:00:37.603+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:00:37.616+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:00:37.650+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:00:37.650+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T08:00:37.678+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:00:37.678+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-16T00:00:00+00:00, run_after=2024-02-16T01:00:00+00:00
[2024-02-29T08:00:37.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.118 seconds
[2024-02-29T08:01:08.185+0000] {processor.py:161} INFO - Started process (PID=3868) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:01:08.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T08:01:08.187+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:01:08.187+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:01:08.201+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:01:08.231+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:01:08.231+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T08:01:08.261+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:01:08.261+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-17T16:00:00+00:00, run_after=2024-02-17T17:00:00+00:00
[2024-02-29T08:01:08.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.109 seconds
[2024-02-29T08:01:38.917+0000] {processor.py:161} INFO - Started process (PID=3983) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:01:38.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T08:01:38.918+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:01:38.918+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:01:38.931+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:01:38.953+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:01:38.952+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T08:01:38.972+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:01:38.972+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-19T07:00:00+00:00, run_after=2024-02-19T08:00:00+00:00
[2024-02-29T08:01:38.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.076 seconds
[2024-02-29T08:02:09.275+0000] {processor.py:161} INFO - Started process (PID=4021) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:02:09.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T08:02:09.276+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:02:09.276+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:02:09.286+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:02:09.308+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:02:09.308+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T08:02:09.331+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:02:09.331+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-19T07:00:00+00:00, run_after=2024-02-19T08:00:00+00:00
[2024-02-29T08:02:09.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.095 seconds
[2024-02-29T08:02:39.700+0000] {processor.py:161} INFO - Started process (PID=4067) to work on /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:02:39.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_api_dag.py for tasks to queue
[2024-02-29T08:02:39.705+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:02:39.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:02:39.731+0000] {processor.py:840} INFO - DAG(s) 'weather_api_dag' retrieved from /opt/airflow/dags/weather_api_dag.py
[2024-02-29T08:02:39.760+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:02:39.760+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-29T08:02:39.785+0000] {logging_mixin.py:188} INFO - [2024-02-29T08:02:39.785+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_api_dag to 2024-02-19T07:00:00+00:00, run_after=2024-02-19T08:00:00+00:00
[2024-02-29T08:02:39.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_api_dag.py took 0.111 seconds
